#include <stdio.h>
#include <ctype.h>
#include <cs50.h>

int main(void)
{
    // we can start by creating a function, which consists of prolly 2 arrays, which contain the characters and 
    // their score count respectiv.. 
    // match them one by one with the characters in the given string 
    // now u have 2 options (maybe more) to proceed
    // either use a for loop again, and keep adding those characters index into an array which will later be used to get the scores
    // or just when u get the character, match it with characters array and suddenly pass that found index into the number array
    // and have a counter variable there or inside the other method
    // first one seems pretty simple since both contain 2 forloops tho
    // the function can take an array generated by normalising the casing to lower
}