#include <stdio.h>
#include <ctype.h>
#include <cs50.h>
#include <string.h>

int score_handler(string input);
void lower(string word);

int main(void)
{
    // the function can take an array generated by normalising the casing to lower
    string word1 = get_string("Player 1: ");
    string word2 = get_string("Player 2: ");
    lower(word1);
    lower(word2);

    if (score_handler(word1) > score_handler(word2))
    {
        printf("Player 1 wins\n");
    }
    else if (score_handler(word1) < score_handler(word2))
    {
        printf("Player 2 wins\n");
    }
    else
    {
        printf("Tie\n");
    }

}

int score_handler(string input)
{
    char chars[] = "abcdefghijklmnopqrstuvwxyz";
    int scores[] = {1,3,3,2,1,4,2,4,1,8,5,1,3,1,1,3,10,1,1,1,1,4,4,8,4,10};
    int n = strlen(input);
    int sum = 0;

    // rather then a while loop and a for loop, use a single for loop with 2 conditionals and infinity safe logic
    for (int i = 0, p = 0; true ; i++)
    {
        // start by matching character from input in chars
        if (input[p] != chars[i])
        {
            if (p == n) {break;}
            else {continue;}
        }
        else
        {
            sum += scores[i];
            p++;
            i = 0;
        }
    }
    return sum;
}        

void lower(string word)
{   
    int n = strlen(word);
    for (int i = 0; i < n; i++)
    {
        word[i] = tolower(word[i]);
    }   
}


